#!/usr/bin/env bash
# This script activates the virtual environment for the scivocab webapp,
# creating it if it doesn't exist.
# Usage: ./create_venv

# Set the ROOT environment variable, assuming that the directory structure
# mirrors that of the git repository.
ROOT="$(cd "$( dirname "${BASH_SOURCE[0]}" )/../" >/dev/null 2>&1 && pwd)"
export ROOT

# Set path to the directory in which we want our virtual environment to live.
venv_dir="$ROOT"/scivocab_venv
if [[ ! -d "$venv_dir" ]]; then
    echo "We did not find the virtual environment directory ${venv_dir}."
    echo "Thus, we will create it now."
    python3 -m venv "$venv_dir"
    . "$venv_dir"/bin/activate
fi
