"""users table





Revision ID: 85498425462c
Revises: 
Create Date: 2020-11-25 13:59:32.657852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85498425462c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_child_id', table_name='user')
    op.drop_index('ix_user_proctor', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('child_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('proctor', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_proctor', 'user', ['proctor'], unique=1)
    op.create_index('ix_user_child_id', 'user', ['child_id'], unique=1)
    # ### end Alembic commands ###
