#!/usr/bin/env bash

# This script creates the virtual environment for the project if it doesn't exist.
# Usage: ./create_virtualenv

# Set the ROOT environment variable, assuming that the directory structure
# mirrors that of the git repository.
ROOT="$(cd "$( dirname "${BASH_SOURCE[0]}" )/../" >/dev/null 2>&1 && pwd)"
export ROOT

# Set path to the directory in which we want our virtual environment to live.
export VENV_DIR="$ROOT"/scivocab_venv

if [[ ! -d "$VENV_DIR" ]]; then
    echo "We did not find the virtual environment directory ${VENV_DIR}."
    echo "Thus, we will create it now."
    python3 -m venv "$VENV_DIR"
fi
