#!/usr/bin/env bash
# This script activates the virtual environment for the scivocab webapp,
# creating it if it doesn't exist. After that, it installs the prerequisites
# for the app.
# Usage: ./install

set -euo pipefail

# Set the ROOT environment variable, assuming that the directory structure
# mirrors that of the git repository.
ROOT="$(cd "$( dirname "${BASH_SOURCE[0]}" )/../" >/dev/null 2>&1 && pwd)"
export ROOT

# For macOS, we do a few things differently, assuming MacPorts has been
# installed.
if [[ $OSTYPE == "darwin"* ]]; then
    # Add MacPorts path
    export PATH=$PATH:/opt/local/bin:/opt/local/sbin

    # Install Python and pip
    PYTHON_VERSION=39
    sudo port selfupdate
    sudo port install py$PYTHON_VERSION-pip

    echo "Activating Python installed by MacPorts"
    sudo port select python python$PYTHON_VERSION
    sudo port select python3 python$PYTHON_VERSION
    sudo port select pip pip$PYTHON_VERSION
    sudo port select pip3 pip$PYTHON_VERSION
fi

$ROOT/tools/create_virtualenv

. $ROOT/scivocab_venv/bin/activate

pip install wheel
pip install -e .
