#!/usr/bin/env bash
# This script activates the virtual environment for the scivocab webapp,
# creating it if it doesn't exist. After that, it installs the prerequisites
# for the app.
# Usage: ./install

set -euo pipefail

# Set the ROOT environment variable, assuming that the directory structure
# mirrors that of the git repository.
ROOT="$(cd "$( dirname "${BASH_SOURCE[0]}" )/../" >/dev/null 2>&1 && pwd)"
export ROOT

# For macOS, we do a few things differently, assuming MacPorts has been
# installed.
if [[ $OSTYPE == "darwin"* ]]; then
    # Add MacPorts path
    export PATH=$PATH:/opt/local/bin:/opt/local/sbin

    # Install Python and pip
    PYTHON_VERSION=39
    sudo port install py$PYTHON_VERSION-pip

    echo "Activating Python installed by MacPorts"
    sudo port select --set python python$PYTHON_VERSION
    sudo port select --set python3 python$PYTHON_VERSION
    sudo port select --set pip pip$PYTHON_VERSION
    sudo port select --set pip3 pip$PYTHON_VERSION
fi


# Set path to the directory in which we want our virtual environment to live.
VENV_DIR="$ROOT"/scivocab_venv

if [[ ! -d "$VENV_DIR" ]]; then
    echo "We did not find the virtual environment directory ${VENV_DIR}."
    echo "Thus, we will create it now."
    python3 -m venv "$VENV_DIR"
fi

. "$VENV_DIR"/bin/activate
pip install -r "$ROOT"/requirements.txt
