#!/usr/bin/env bash

# Set the ROOT environment variable, assuming that the directory structure
# mirrors that of the git repository.
ROOT="$(cd "$( dirname "${BASH_SOURCE[0]}" )/../" >/dev/null 2>&1 && pwd)"
export ROOT


# Create the virtual environment if it doesn't exist
"$ROOT"/tools/create_virtualenv


. scivocab_venv/bin/activate

pushd $ROOT/app
    FLASK_DEBUG=1 python main.py
popd
