#!/usr/bin/env bash

# Set the ROOT environment variable, assuming that the directory structure
# mirrors that of the git repository.
ROOT="$(cd "$( dirname "${BASH_SOURCE[0]}" )/../" >/dev/null 2>&1 && pwd)"
export ROOT


# Create or activate the virtual environment.
#"$ROOT"/tools/activate_virtualenv

pushd $ROOT/app
    FLASK_DEBUG=1 python main.py
popd
