#!/usr/bin/env bash

# Set the ROOT environment variable, assuming that the directory structure
# mirrors that of the git repository.
ROOT="$(cd "$( dirname "${BASH_SOURCE[0]}" )/../" >/dev/null 2>&1 && pwd)"
export ROOT

pushd $ROOT
    . scivocab_venv/bin/activate
    pushd app
        FLASK_DEBUG=1 python main.py
    popd
popd
