#!/usr/bin/env python
import sys
import pandas as pd
from sqlalchemy import create_engine


if __name__ == "__main__":
    # Connect to the database
    print(sys.argv)
    uri = "sqlite:///"+sys.argv[1]
    print(uri)
    engine = create_engine(uri)
    df = pd.read_sql(
        """select
            child_id,
            word.id as word_id,
            definition_id,
            strand_id,
            word.target as target_word,
            text,
            score,
            timestamp
        from definition_response
        inner join word on
        definition_response.word_id=word.id;""",
        engine,
        parse_dates=["timestamp"],
    )

    df.to_excel(sys.argv[2], engine="openpyxl")
